### ISSUE TITLE
Does this project have an active maintainer?

### ISSUE THREAD

**Issue by XavierChanth** [TerminalStudio/dartssh2#98]
It's been over a year since any changes were published for this package, and given that it is an ssh library. It would be good to know that someone is keeping up with any potential security issues that may arise now or in the future.

**Comment by vicajilau** [comment]
Due to the inactivity of this repository and the need to maintain it within one of the Google Summer of Code organizations in which I collaborate. If anyone else needs it, [this is the new repository](https://github.com/vicajilau/dartssh4) created from this one with this change (and others applied).

**Comment by vicajilau** [comment]
Yes, this is still maintained. Many thanks for your time 🚀
